Controllers films users
PolinaShmargunova/java-filmorate pull request #4
Opened 2023-01-25 18:35 UTC by PolinaShmargunova

2023-01-26 19:31 UTC, z8q requested changes
Привет, Полина!

Код посмотрел, оставил предложения для доработки.
В целом, конструкции применяются верно. Логика соответствует ТЗ

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return films.values();
Можно было бы возвращать new ArrayList<>(films.values())

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.remove(film.getId());
Было бы правильно сразу добавлять  в мапу:
films.put(film.getId(), film);
Результат будет такой же

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film updateFilm(Film film) throws RuntimeException {
RuntimeException – Unchecked Exception
Непроверяемые исключения не требуют обрабатывать их в try catch, и не требуют прокидывать их выше.
throws RuntimeException – можно убрать

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return users.values();
К UserService тоже применимы комментарии из FilmService:
new ArrayList<>(users.values());

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(HashMap<Object, Object> objectHashMap) {
У нас есть конструктор, который принимает аргумент, но мы его не используем.
Может тогда совсем убрать.
И нужна ли здесь аннтоация @RequiredArgsConstructor?

2023-01-26 19:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@RequiredArgsConstructor
Зачем здесь эта аннотация?
new FilmService(new HashMap<>()) – в таком создании объекта нет большого смысла.
Можно сразу задать мапу:
private final Map<Integer, Film> films = new HashMap<>();
И убрать аннотацию

2023-01-26 19:31 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(exception.getMessage(), exception.getMessage());
Мы сравниваем сообщения из одного и того же объекта. Они же всегда будут одинаковы.
Выше есть такие же конструкции

2023-01-26 19:31 UTC, z8q commented on pom.xml
> +        </dependency>
Можно было бы попробовать поработать с
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
и его аннотациями: @NotNull, @NotBlank, @Email и т.д.

2023-01-27 15:28 UTC, PolinaShmargunova commented on pom.xml
> +        </dependency>
Согласно ТЗ, работа с этими аннотациями не является обязательным заданием, поэтому их в свою работу я не включала

2023-01-28 10:34 UTC, z8q approved these changes

2023-01-28 10:36 UTC, merged